export const skillsData =[
                    {
                        id: "html",
                        skillName: "HTML",
                        stars: 3,
                        imgUrl: "./icons/html.png",
                        skillgroup: "basicFrontend",
                        isInvisible: false,
                    },
                    {
                        id: "css",
                        skillName: "CSS",
                        stars: 3,
                        imgUrl: "./icons/css.png",
                        skillgroup: "basicFrontend",
                        isInvisible: false,
                    },
                    {
                        id: "javascript",
                        skillName: "Javascript",
                        stars: 3,
                        imgUrl: "./icons/javascript.png",
                        skillgroup: "basicFrontend",
                        isInvisible: false,
                    },

                    {
                        id: "react",
                        skillName: "React",
                        stars: 3,
                        imgUrl: "./icons/react.png",
                        skillgroup: "frameworks",
                        isInvisible: false,
                    },
                    {
                        id: "vue",
                        skillName: "Vue",
                        stars: 3,
                        imgUrl: "./icons/vue.png",
                        skillgroup: "frameworks",
                        isInvisible: false,
                    },

                    // {
                    //     id:"nextjavascript",
                    //     skillName:"Nextjavascript",
                    //     stars:1,
                    //     imgUrl:"./icons/next_javascript.png",
                    //     skillgroup:"frameworks",
                    //     isInvisible:false
                    // },

                    {
                        id: "angular",
                        skillName: "Angular",
                        stars: 1,
                        imgUrl: "./icons/angular.png",
                        skillgroup: "frameworks",
                        isInvisible: false,
                    },
                    {
                        id: "typescript",
                        skillName: "Typescript",
                        stars: 2,
                        imgUrl: "./icons/typescript.png",
                        skillgroup: "advanceFrontend",
                        isInvisible: false,
                    },

                    {
                        id: "jquery",
                        skillName: "jquery",
                        stars: 2,
                        imgUrl: "./icons/jquery.png",
                        skillgroup: "advanceFrontend",
                        isInvisible: false,
                    },

                    {
                        id: "sass",
                        skillName: "Sass",
                        stars: 3,
                        imgUrl: "./icons/sass.png",
                        skillgroup: "advanceFrontend2",
                        isInvisible: false,
                    },
                    {
                        id: "tailwind",
                        skillName: "Tailwind",
                        stars: 3,
                        imgUrl: "./icons/tailwind.png",
                        skillgroup: "advanceFrontend2",
                        isInvisible: false,
                    },
                    {
                        id: "bootstrap",
                        skillName: "Bootstrap",
                        stars: 3,
                        imgUrl: "./icons/bootstrap.png",
                        skillgroup: "advanceFrontend2",
                        isInvisible: false,
                    },
                    {
                        id: "material_ui",
                        skillName: "MUI",
                        stars: 2,
                        imgUrl: "./icons/material_ui.png",
                        skillgroup: "advanceFrontend2",
                        isInvisible: false,
                    },

                    {
                        id: "node",
                        skillName: "Node",
                        stars: 2,
                        imgUrl: "./icons/node.png",
                        skillgroup: "backendNode",
                        isInvisible: false,
                    },
                    {
                        id: "express",
                        skillName: "Express",
                        stars: 2,
                        imgUrl: "./icons/express.png",
                        skillgroup: "backendNode",
                        isInvisible: false,
                    },

                    {
                        id: "python",
                        skillName: "Python",
                        stars: 3,
                        imgUrl: "./icons/python.png",
                        skillgroup: "backendPython",
                        isInvisible: false,
                    },
                    {
                        id: "django",
                        skillName: "Django",
                        stars: 2,
                        imgUrl: "./icons/django.png",
                        skillgroup: "backendPython",
                        isInvisible: false,
                    },
                    {
                        id: "flask",
                        skillName: "Flask",
                        stars: 2,
                        imgUrl: "./icons/flask.png",
                        skillgroup: "backendPython",
                        isInvisible: false,
                    },
                    {
                        id: "php",
                        skillName: "PHP",
                        stars: 2,
                        imgUrl: "./icons/php.png",
                        skillgroup: "backendPHP",
                        isInvisible: false,
                    },
                    {
                        id: "synfony",
                        skillName: "Synfony",
                        stars: 2,
                        imgUrl: "./icons/symfony.png",
                        skillgroup: "backendPHP",
                        isInvisible: false,
                    },
                    {
                        id: "laravel",
                        skillName: "Laravel",
                        stars: 0,
                        imgUrl: "./icons/laravel.png",
                        skillgroup: "backendPHP",
                        isInvisible: false,
                    },
                    {
                        id: "aws",
                        skillName: "AWS",
                        stars: 2,
                        imgUrl: "./icons/aws.png",
                        skillgroup: "cloudService",
                        isInvisible: false,
                    },
                    {
                        id: "firebase",
                        skillName: "Firebase",
                        stars: 2,
                        imgUrl: "./icons/firebase.png",
                        skillgroup: "cloudService",
                        isInvisible: false,
                    },
                    {
                        id: "azure",
                        skillName: "Azure",
                        stars: 2,
                        imgUrl: "./icons/azure.png",
                        skillgroup: "cloudService",
                        isInvisible: false,
                    },

                    {
                        id: "drupal",
                        skillName: "Drupal",
                        stars: 2,
                        imgUrl: "./icons/drupal.png",
                        skillgroup: "cms",
                        isInvisible: false,
                    },
                    {
                        id: "wordpress",
                        skillName: "Wordpress",
                        stars: 1,
                        imgUrl: "./icons/word_press.png",
                        skillgroup: "cms",
                        isInvisible: false,
                    },
                    {
                        id: "figma",
                        skillName: "Figma",
                        stars: 3,
                        imgUrl: "./icons/figma.png",
                        skillgroup: "otherSkills",
                        isInvisible: false,
                    },
                    {
                        id: "mysql",
                        skillName: "MySQL",
                        stars: 2,
                        imgUrl: "./icons/mysql.png",
                        skillgroup: "otherSkills",
                        isInvisible: false,
                    },
                    {
                        id: "git",
                        skillName: "Git",
                        stars: 3,
                        imgUrl: "./icons/git.png",
                        skillgroup: "otherSkills",
                        isInvisible: false,
                    },
                    {
                        id: "canva",
                        skillName: "Canva",
                        stars: 2,
                        imgUrl: "./icons/canva.png",
                        skillgroup: "otherSkills",
                        isInvisible: false,
                    },

                    {
                        id: "dotnet",
                        skillName: ".Net",
                        stars: 1,
                        imgUrl: "./icons/dot_net.png",
                        skillgroup: "embedSystems",
                        isInvisible: false,
                    },
                    {
                        id: "c",
                        skillName: "C",
                        stars: 1,
                        imgUrl: "./icons/c.png",
                        skillgroup: "embedSystems",
                        isInvisible: false,
                    },
                    {
                        id: "cpp",
                        skillName: "C++",
                        stars: 1,
                        imgUrl: "./icons/c++.png",
                        skillgroup: "embedSystems",
                        isInvisible: false,
                    },
                    {
                        id: "cs",
                        skillName: "C#",
                        stars: 1,
                        imgUrl: "./icons/csharp.png",
                        skillgroup: "embedSystems",
                        isInvisible: false,
                    },
                    // {
                    //   id: "java",
                    //   skillName: "Java",
                    //   stars: 1,
                    //   imgUrl: "./icons/java.png",
                    //   skillgroup: "backendJava",
                    //   isInvisible: true,
                    // },
                    // {
                    //   id: "spring",
                    //   skillName: "Spring",
                    //   stars: 1,
                    //   imgUrl: "./icons/spring.png",
                    //   skillgroup: "backendJava",
                    //   isInvisible: true,
                    // },
                    {
                        id: "kubernetes",
                        skillName: "Kubernetes",
                        stars: 1,
                        imgUrl: "./icons/kubernetes.png",
                        skillgroup: "cicd",
                        isInvisible: false,
                    },
                    {
                        id: "jenkins",
                        skillName: "Jenkins",
                        stars: 1,
                        imgUrl: "./icons/jenkins.png",
                        skillgroup: "cicd",
                        isInvisible: false,
                    },
                    {
                        id: "sonarcube",
                        skillName: "SonarQube",
                        stars: 1,
                        imgUrl: "./icons/sonarqube.png",
                        skillgroup: "cicd",
                        isInvisible: false,
                    },
                    {
                        id: "twig",
                        skillName: "Twig",
                        stars: 3,
                        imgUrl: "./icons/twig.png",
                        skillgroup: "templating",
                        isInvisible: false,
                    },
                    {
                        id: "ejs",
                        skillName: "EJS",
                        stars: 3,
                        imgUrl: "./icons/ejs.png",
                        skillgroup: "templating",
                        isInvisible: false,
                    },
                    {
                        id: "pug",
                        skillName: "Pug",
                        stars: 2,
                        imgUrl: "./icons/pug.png",
                        skillgroup: "templating",
                        isInvisible: false,
                    },
                    {
                        id:"appwrite",
                        skillName:"AppWrite",
                        stars:2,
                        imgUrl:"./icons/appwrite.png",
                        skillgroup:"otherSkills",
                        isInvisible:false
                    },
                    {
                        id:"unity",
                        skillName:"Unity",
                        stars:2,
                        imgUrl:"./icons/unity.png",
                        skillgroup:"otherSkills",
                        isInvisible:false
                    },
                    {
                        id:"server",
                        skillName:"Server",
                        stars:3,
                        imgUrl:"./icons/windows_server.png",
                        skillgroup:"itSupport",
                        isInvisible:false
                    },
                    {
                        id:"remote_desktop",
                        skillName:"Remote",
                        stars: 3,
                        imgUrl:"./icons/remote_desktop.png",
                        skillgroup:"itSupport",
                        isInvisible:false
                    },
                    {
                        id:"vmware",
                        skillName:"vmware",
                        stars:3,
                        imgUrl:"./icons/vmware.png",
                        skillgroup:"itSupport",
                        isInvisible:false
                    },
                    {
                        id:"m365",
                        skillName:"M365",
                        stars:2,
                        imgUrl:"./icons/m365.svg",
                        skillgroup:"cloudService",
                        isInvisible:false
                    },
                    // {
                    //     id:"",
                    //     skillName:"",
                    //     stars:,
                    //     imgUrl:"",
                    //     skillgroup:"",
                    //     isInvisible:false
                    // },
    ]

export const projectsData = [
  {
    id: "gradients",
    title: "Gradients",
    type: "primary",
    link: "https://victor-grinan-dev.github.io/color_gradients/",
    imgUrl: "./images/02gradients.JPG",
    description: "Getting familiar with HTML & CSS",
    sectionId: "schoolProjects",
    repoLink: "color_gradients",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "html",
    technologies: ["javascript", "css"],
    deployed: "github",
  },
  // {
  //   id: "speedGame",
  //   title: "Speed Game",
  //   type: "primary",
  //   link: "https://victor-grinan-dev.github.io/speed_game/",
  //   imgUrl: "./images/speedgame.JPG",
  //   description: "Using javascript to handle the DOM",
  //   sectionId: "schoolProjects",
  //   repoLink: "speed_game",
  //   repoSite: "https://github.com/Victor-Grinan-Dev/",
  //   framework: "html",
  //   technologies: ["javascript", "css"],
  // deployed:'github'
  // },
  {
    id: "pokemons",
    title: "Pokedex",
    type: "primary",
    link: "https://victor-grinan-dev.github.io/react_pokemons/",
    imgUrl: "./images/pokemons.jpg",
    description: "Learning to fetch and display data",
    sectionId: "schoolProjects",
    repoLink: "react_pokemons ",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["axios"],
    deployed: "github",
  },
  {
    id: "keeperApp",
    title: "Keeper App",
    type: "primary",
    link: "https://jocular-tapioca-476ffa.netlify.app/",
    imgUrl: "./images/keeperApp.jpg",
    description: "Combining the use of local storage & MUI styling",
    sectionId: "schoolProjects",
    repoLink: "keeper_app",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["material_ui"],
    deployed: "netlify",
  },
  /*{
    id: "foodApp",
    title: "Food App",
    type: "primary",
    link: "https://food-app4.netlify.app/",
    //https://victor-grinan-dev.github.io/food-app3/
    imgUrl: "./images/feelit_cookit.png",
    description: "Handling a CRUD",
    sectionId: "schoolProjects",
    repoLink: "food-app4",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["axios", "firebase"],
    deployed: "netlify",
  },*/
  {
    id: "countriesApp",
    title: "Countries App",
    type: "primary",
    link: "https://countries-tau-ashy.vercel.app/",
    imgUrl: "./images/countries.png",
    description: "Introduction to redux",
    sectionId: "schoolProjects",
    repoLink: "countries_app",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["redux", "axios", "bootstrap"],
    deployed: "github",
  },
  {
    id: "diceRoller",
    title: "Dice Roller",
    type: "primary",
    link: "https://victor-grinan-dev.github.io/diceRoller",
    imgUrl: "./images/diceRoller.JPG",
    description: "My first HTML, CSS & javascript",
    sectionId: "personalProjects",
    repoLink: "diceRoller",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "html",
    technologies: ["javascript", "css"],
    deployed: "github",
  },
  {
    id: "simonsays",
    title: "Simon Says",
    type: "primary",
    link: "https://simon-game-opal-eta.vercel.app/ ",
    imgUrl: "./images/simonsays.png",
    description: "Exercise from udemy",
    sectionId: "sillyGames",
    repoLink: "11Simon-Game",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "html",
    technologies: ["javascript", "css", "jquery"],
    deployed: "vercel",
  },

  {
    id: "turnTimer",
    title: "Turn Timer",
    type: "primary",
    link: "https://victor-grinan-dev.github.io/blood_bowl_turn_timer/",
    imgUrl: "./images/turn_timer.JPG",
    description: "first site for my Hobby group",
    sectionId: "personalProjects",
    repoLink: "blood_bowl_turn_timer",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "html",
    technologies: ["javascript", "css"],
    deployed: "github",
  },
  // {
  //   id: "hexMap",
  //   title: "Hex Map",
  //   type: "primary",
  //   link: "https://victor-grinan-dev.github.io/map-creator/",
  //   imgUrl: "./images/hexMap.JPG",
  //   description: "Getting use to mapping in javascript",
  //   sectionId: "personalProjects",
  //   repoLink: "map-creator",
  //   repoSite: "https://github.com/Victor-Grinan-Dev/",
  //   framework: "html",
  //   technologies: ["javascript", "css"],
  //   deployed: "github",
  // },
  {
    id: "mapCreator",
    title: "Campaign Tracker: Map Creator",
    type: "primary",
    // link: "https://enchanting-taiyaki-964ff9.netlify.app/",
    link: "https://hilarious-klepon-7fac2f.netlify.app/",
    imgUrl: "./images/campaign-tracker.png",
    description: "Demo day project from school",
    sectionId: "personalProjects",
    repoLink: "campaign-tracker-demo",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["redux"],
    deployed: "netlify",
  },
  // {
  //   id: "unit_creator",
  //   title: "Campaign Tracker: Unit Creator",
  //   type: "primary",
  //   // link: "https://enchanting-taiyaki-964ff9.netlify.app/",
  //   link: "https://hilarious-klepon-7fac2f.netlify.app/",
  //   imgUrl: "./images/campaign-tracker.png",
  //   description: "Demo day project from school",
  //   sectionId: "personalProjects",
  //   repoLink: "campaign-tracker-demo",
  //   repoSite: "https://github.com/Victor-Grinan-Dev/",
  //   framework: "react",
  //   technologies: ["redux"],
  //   deployed:'netlify'
  // },
  {
    id: "theGame",
    title: "Campaign Tracker: The Game",
    type: "primary",
    link: "https://classy-vacherin-e654f9.netlify.app/",
    video: "https://www.youtube.com/watch?v=YPBy4kEFNVQ",
    imgUrl: "./images/the_game.png",
    description: 'The demo of the game "Campaing Tracker"',
    sectionId: "personalProjects",
    repoLink: "the_game",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["redux"],
    deployed: "netlify",
  },
  {
    id: "40k-tool",
    title: "40k-Tool",
    type: "primary",
    link: "https://40k-tool.vercel.app/",
    video: "",
    imgUrl: "./images/40ktool.png",
    description: "Work in progress to help my gaming comunity",
    sectionId: "personalProjects",
    repoLink: "the_game",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["redux", "sass"],
    deployed: "vercel",
  },
  {
    id: "theCubanShow",
    title: "The Cuban Show",
    type: "primary",
    // link: "https://thecubanshow.com/",
    link: "https://the-cuban-show-development.netlify.app/",
    imgUrl: "./images/thecubanshow.png",
    description: "First serious job for a friend",
    sectionId: "freelancer",
    repoLink: "the_cuban_show_ui",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["firebase", "axios", "redux"],
    deployed: "netlify",
  },
  {
    id: "Kerttu",
    title: "Kerttu",
    type: "primary",
    link: "https://kerttu.vercel.app/",
    video: "",
    imgUrl: "./images/kerttu.png",
    description: "A friend request for her daugther's bd",
    sectionId: "freelancer",
    repoLink: "the_game",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "html",
    technologies: ["javascript", "sass"],
    deployed: "vercel",
  },
  {
    id: "tailwindLoopstudios",
    title: "Tailwind Loopstudios",
    type: "primary",
    link: "https://loopstodios-react.vercel.app/",
    imgUrl: "./images/loopstudios.png",
    description: "Tailwind learning exercise, no func.",
    sectionId: "internet",
    repoLink: "loopstudio-react",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["tailwind"],
    deployed: "vercel",
  },
  {
    id: "tailwindShortly",
    title: "Tailwind Shortly",
    type: "primary",
    link: "https://shortly-react-nine.vercel.app/",
    imgUrl: "./images/shortly.png",
    description: "Tailwind learning exercise, no func.",
    sectionId: "internet",
    repoLink: "shortly-react",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["tailwind"],
    deployed: "vercel",
  },
  {
    id: "tailwindGallery",
    title: "Tailwind Gallery",
    type: "primary",
    link: "https://image-gallery-react-nu.vercel.app/",
    imgUrl: "./images/gallery.png",
    description: "Tailwind learning exercise, no func.",
    sectionId: "internet",
    repoLink: "image-gallery-react",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["tailwind"],
    deployed: "vercel",
  },
  {
    id: "tailwindPrices",
    title: "Tailwind Price cards",
    type: "primary",
    link: "https://card-price.vercel.app/",
    imgUrl: "./images/priceCards.png",
    description: "Tailwind learning exercise, no func.",
    sectionId: "internet",
    repoLink: "price-cards-react",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["tailwind"],
    deployed: "vercel",
  },
  {
    id: "tailwindLogin",
    title: "Tailwind Login Modal",
    type: "primary",
    link: "https://login-modal-rho.vercel.app/",
    imgUrl: "./images/login.png",
    description: "Tailwind learning exercise, no func.",
    sectionId: "internet",
    repoLink: "login-modal-react",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["tailwind"],
    deployed: "vercel",
  },
  {
    id: "tailwindProduct",
    title: "Tailwind Product Modal",
    type: "primary",
    link: "https://product-modal-react.vercel.app/",
    imgUrl: "./images/product.png",
    description: "Tailwind learning exercise, no func.",
    sectionId: "internet",
    repoLink: "product-modal-react",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["tailwind"],
    deployed: "vercel",
  },
  {
    id: "tailwindLandingPage",
    title: "Tailwind Landing Page",
    type: "primary",
    link: "https://landing-page-react-jet.vercel.app/",
    imgUrl: "./images/landing.png",
    description: "Tailwind learning exercise, no func.",
    sectionId: "internet",
    repoLink: "landing-page-react",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["tailwind"],
    deployed: "vercel",
  },
  {
    id: "testimonialGrid",
    title: "Tailwind Testimonial Grid",
    type: "primary",
    link: "https://testimonial-grid-alpha.vercel.app/",
    imgUrl: "./images/testimonialGrid.png",
    description: "Tailwind learning exercise, no func.",
    sectionId: "internet",
    repoLink: "testimonial-grid",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["tailwind"],
    deployed: "vercel",
  },
  {
    id: "fylo",
    title: "Tailwind Fylo",
    type: "primary",
    link: "https://vercel.com/victor-grinan-dev/fylo-react",
    imgUrl: "./images/fylo.png",
    description: "Tailwind learning exercise, no func.",
    sectionId: "internet",
    repoLink: "fylo-react",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["tailwind"],
    deployed: "vercel",
  },
  {
    id: "bookmarkManager",
    title: "Tailwind Bookmark Manager",
    type: "primary",
    link: "https://bookmark-manager-react.vercel.app/",
    imgUrl: "./images/bookmark.png",
    description: "Tailwind learning exercise, no func.",
    sectionId: "internet",
    repoLink: "bookmark-manager-react",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["tailwind"],
    deployed: "vercel",
  },
  {
    id: "natour",
    title: "Sass Natour",
    type: "primary",
    link: "https://natour-eta.vercel.app/",
    imgUrl: "./images/natour.png",
    description: "Sass learning exercise, no func.",
    sectionId: "internet",
    repoLink: "natour",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "html",
    technologies: ["sass"],
    deployed: "vercel",
  },
  {
    id: "nexter",
    title: "Sass Nexter",
    type: "primary",
    link: "https://nexter-ui.vercel.app/",
    imgUrl: "./images/nexter.png",
    description: "Sass learning exercise, no func.",
    sectionId: "internet",
    repoLink: "nexter-ui",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "html",
    technologies: ["sass"],
    deployed: "vercel",
  },
  {
    id: "trillo",
    title: "Sass Trillo",
    type: "primary",
    link: "https://trillo-nu.vercel.app/",
    imgUrl: "./images/trillo.png",
    description: "Sass learning exercise, no func.",
    sectionId: "internet",
    repoLink: "trillo",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "html",
    technologies: ["sass"],
    deployed: "vercel",
  },
  {
    id: "first vue",
    title: "My First Vue",
    type: "primary",
    link: "https://victor-grinan-dev.github.io/my-first-vue-app/",
    imgUrl: "./images/my_first_vue.png",
    description: "First steps in vue framework using CDN.",
    sectionId: "internet",
    repoLink: "my-first-vue-app",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "vue",
    technologies: ["html", "javascript", "css"],
    deployed: "github",
  },
  {
    id: "random-user-generator-vue",
    title: "Random User Generator",
    type: "primary",
    link: "https://random-user-generator-vue.vercel.app/",
    imgUrl: "./images/random-user-gen.png",
    description: "Fetching api in vue framework using CDN.",
    sectionId: "internet",
    repoLink: "random-user-generator-vue",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "vue",
    technologies: ["html", "javascript", "css"],
    deployed: "vercel",
  },
  {
    id: "vue_monster_slayer",
    title: "Monster Slayer",
    type: "primary",
    link: "https://vue-monster-slayer-beta.vercel.app/",
    imgUrl: "./images/vue-monster-slayer.png",
    description: "Dominating the DOM with Vue.",
    sectionId: "internet",
    repoLink: "project-01-monster-slayer",
    repoSite: "https://github.com/Victor-Grinan-Dev/vue_guide/tree/main/",
    framework: "vue",
    technologies: ["html", "javascript", "css"],
    deployed: "vercel",
  },
  {
    id: "resource_manager",
    title: "Resource Manager",
    type: "primary",
    link: "https://resource-manager-xi.vercel.app/",
    imgUrl: "./images/vue-resorce-manager.png",
    description: "Learning components and app structure in Vue.",
    sectionId: "internet",
    repoLink: "resource-manager",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "vue",
    technologies: ["html", "javascript", "css"],
    deployed: "vercel",
  },
  {
    id: "survey_app",
    title: "Survey App",
    type: "primary",
    link: "https://survey-app-lyart-ten.vercel.app/",
    imgUrl: "./images/survey-app.png",
    description: "POST & GET from Firebase DB",
    sectionId: "internet",
    repoLink: "survey-app",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "vue",
    technologies: ["html", "javascript", "css", "axios", "firebase"],
    deployed: "vercel",
  },
  // {
  //   id: "teams-&-users",
  //   title: "Teams & Users",
  //   type: "primary",
  //   link: "https://teams-users.vercel.app/",
  //   imgUrl: "./images/teams-&-users.png",
  //   description: "Routing in Vue",
  //   sectionId: "internet",
  //   repoLink: "teams---users",
  //   repoSite: "https://github.com/Victor-Grinan-Dev/",
  //   framework: "vue",
  //   technologies: ["html", "javascript", "css", "axios", "firebase"],
  //   deployed:'vercel'
  // },
  {
    id: "vue_animations",
    title: "Vue Animations",
    type: "primary",
    link: "https://vue-animations-seven.vercel.app/",
    imgUrl: "./images/vue_animations.png",
    description: "POST & GET from Firebase DB",
    sectionId: "internet",
    repoLink: "vue-animations",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "vue",
    technologies: ["html", "javascript", "css"],
    deployed: "vercel",
  },
  {
    id: "vuex_online_store",
    title: "Vue Online Store",
    type: "primary",
    link: "https://vuex-online-store.vercel.app/products",
    imgUrl: "./images/vuex-online-store.png",
    description: "Learning VUEX",
    sectionId: "internet",
    repoLink: "vuex-online-store",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "vue",
    technologies: ["vuex", "html", "javascript", "css"],
    deployed: "vercel",
  },
  {
    id: "vuex_coach_finder",
    title: "Vue Coach Finder",
    type: "primary",
    link: "https://coaches-fdce3.web.app/coaches",
    // link: "https://vue-coach-finder.vercel.app/coaches",
    imgUrl: "./images/vue_coach_finder.png",
    description: "Learning VUEX",
    sectionId: "internet",
    repoLink: "project-06-coach-finder-vue",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "vue",
    technologies: ["vuex", "html", "javascript", "css", "firebase"],
    deployed: "vercel",
  },
  // {
  //     "id":"",
  //     "title":"",
  //     "type":"",
  //     "link":"",
  //     "imgUrl":"",
  //     "description":"",
  //     "sectionId":""
  // }
  {
    id: "malditos_dice",
    title: "Malditos Dice",
    type: "primary",
    link: "https://malditos-dice.vercel.app/",
    video: "",
    imgUrl: "./images/malditos-dice.png",
    description: "For my hobby club (in progress)",
    sectionId: "personalProjects",
    repoLink: "hobby-app",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "vue",
    technologies: ["vuex", "tailwind", "firebase"],
    deployed: "vercel",
  },
  {
    id: "inky11",
    title: "Inky11",
    type: "primary",
    link: "https://www.inky11.com/",
    video: "",
    imgUrl: "./images/inky11.png",
    description: "For a friend busisness",
    sectionId: "freelancer",
    repoLink: "bandida",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: [ "sass"],
    deployed: "netlify",
  },
  {
    id: "fafas_isoroba", 
    title: "Fafa's Iso Roba Schedule",
    type: "primary",
    link: "https://fafas-schedule-test.netlify.app/",
    video: "",
    imgUrl: "./images/fafas.png",
    description: "For the company i'm working partime",
    sectionId: "freelancer",
    repoLink: "fafas_isoroba",
    repoSite: "https://github.com/Victor-Grinan-Dev/",
    framework: "react",
    technologies: ["sass", "redux"],
    deployed: "netlify",
  },
];

export const certificatesData = [
  {
    id: "hbc",
    title: "Qualification in Information Tech",
    docLink: "./documents/HBC_graduation_certificate_small.png",
    section: "mainCertificates",
  },
  {
    id: "pythonBasics",
    title: 'SDA - "Python From Scratch"',
    docLink: "./documents/sda_certificate.png",
    section: "mainCertificates",
  },
  {
    id: "codeCommit",
    title: 'AWS - "CodeCommit"',
    docLink: "./documents/AWS_CodeCommit_Course_Completion_Certificate.png",
    section: "onlineCertificates1",
  },
  {
    id: "DevOps",
    title: 'AWS - "DevOps"',
    docLink: "./documents/AWS_DevOps_Course_Completion_Certificate.png",
    section: "onlineCertificates1",
  },
  {
    id: "EC2",
    title: 'AWS - "Elastic Compute Cloud"',
    docLink: "./documents/AWS_EC2_Completion_Certificate.png",
    section: "onlineCertificates1",
  },
  {
    id: "Namespaces",
    title: 'SfCasts - "PHP Namespaces"',
    docLink: "./documents/sfcasts-VictorGrinan-certificate-php-namespaces.png",
    section: "onlineCertificates2",
  },
  {
    id: "Symfony6",
    title: 'SfCasts - "Symfony 6"',
    docLink:
      "./documents/sfcasts-VictorGrinan-certificate-harmonious-development-with-symfony-6.png",
    section: "onlineCertificates2",
  },
  {
    id: "Composer",
    title: 'SfCasts - "Composer"',
    docLink: "./documents/sfcasts-VictorGrinan-certificate-composer.png",
    section: "onlineCertificates2",
  },
  {
    id: "css",
    title: 'DCourses - "CSS"',
    docLink: "./documents/disc_courses_css.png",
    section: "onlineCertificates3",
  },
  {
    id: "vue",
    title: 'DCourses - "Vue"',
    docLink: "./documents/Vue_Fundamentals.png",
    section: "onlineCertificates3",
  },
  {
    id: "sass",
    title: 'Udemy - "Advanced CSS" - "SASS"',
    docLink: "./documents/udemy_advanced_sass.jpg",
    section: "onlineCertificates4",
  },
  {
    id: "tailwind",
    title: 'Udemy - "Tailwind',
    docLink: "./documents/udemy_tailwind.jpg",
    section: "onlineCertificates4",
  },
  {
    id: "vue-guide",
    title: 'Udemy - "Vue Guide',
    docLink: "./documents/Vue_guide.jpg",
    section: "onlineCertificates4",
  },
  {
    id: "Entrepreneurship",
    title: 'YH - "Entrepreneurship"',
    docLink: "./documents/2015_yrittaja_todistus.png",
    section: "othersCertificates",
  },
  {
    id: "Investing",
    title: 'Udemy - "Investing in stocks"',
    docLink: "./documents/UC-a13b9ecc-951b-4ff9-8856-ee83cca0f6cd.png",
    section: "othersCertificates",
  },
  {
    id: "bachellor",
    title: 'Cuba - "Bachellor In Humanities"',
    docLink: "./documents/Bachiller.jpg",
    section: "othersCertificates",
  },
];